name: mse-fp-hw14
version: 0.1.0.0
github: "winter-yuki/mse-fp-hw14"
license: BSD-3-Clause
author: "Andrey Stoyan"
maintainer: "andrey.stoyan.csam@gmail.com"
copyright: "2023 Andrey Stoyan"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/winter-yuki/mse-fp-hw14#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - pretty
  - GenericPretty
  - random

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -Wno-unrecognised-pragmas
  - -Wno-unused-imports

library:
  source-dirs: src

tests:
  mse-fp-hw14-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-orphans
      - -Wno-type-defaults
    dependencies:
      - mse-fp-hw14
      - HUnit
      - QuickCheck
      - quickcheck-classes-base
      - generic-arbitrary
      - generic-random
